package gov.customs.jm.data;

// Generated Jun 4, 2015 4:42:51 PM by Hibernate Tools 3.4.0.CR1

/**
 * RuleFeedbackData generated by hbm2java
 */
public class RuleFeedbackData implements java.io.Serializable {

	private RuleFeedbackDataId id;

	public RuleFeedbackData() {
	}

	public RuleFeedbackData(RuleFeedbackDataId id) {
		this.id = id;
	}

	public RuleFeedbackDataId getId() {
		return this.id;
	}

	public void setId(RuleFeedbackDataId id) {
		this.id = id;
	}

}
