package gov.customs.jm.data;

// Generated Jun 4, 2015 4:42:51 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RuleFeedbackDataId generated by hbm2java
 */
public class RuleFeedbackDataId implements java.io.Serializable {

	private BigDecimal ruleId;
	private Boolean isFeedback;
	private String feedbackDesc;
	private String businessCode;
	private String hitDesc;
	private String positionDesc;
	private String entityKeys;

	public RuleFeedbackDataId() {
	}

	public RuleFeedbackDataId(BigDecimal ruleId, Boolean isFeedback,
			String feedbackDesc, String businessCode, String hitDesc,
			String positionDesc, String entityKeys) {
		this.ruleId = ruleId;
		this.isFeedback = isFeedback;
		this.feedbackDesc = feedbackDesc;
		this.businessCode = businessCode;
		this.hitDesc = hitDesc;
		this.positionDesc = positionDesc;
		this.entityKeys = entityKeys;
	}

	public BigDecimal getRuleId() {
		return this.ruleId;
	}

	public void setRuleId(BigDecimal ruleId) {
		this.ruleId = ruleId;
	}

	public Boolean getIsFeedback() {
		return this.isFeedback;
	}

	public void setIsFeedback(Boolean isFeedback) {
		this.isFeedback = isFeedback;
	}

	public String getFeedbackDesc() {
		return this.feedbackDesc;
	}

	public void setFeedbackDesc(String feedbackDesc) {
		this.feedbackDesc = feedbackDesc;
	}

	public String getBusinessCode() {
		return this.businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode;
	}

	public String getHitDesc() {
		return this.hitDesc;
	}

	public void setHitDesc(String hitDesc) {
		this.hitDesc = hitDesc;
	}

	public String getPositionDesc() {
		return this.positionDesc;
	}

	public void setPositionDesc(String positionDesc) {
		this.positionDesc = positionDesc;
	}

	public String getEntityKeys() {
		return this.entityKeys;
	}

	public void setEntityKeys(String entityKeys) {
		this.entityKeys = entityKeys;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RuleFeedbackDataId))
			return false;
		RuleFeedbackDataId castOther = (RuleFeedbackDataId) other;

		return ((this.getRuleId() == castOther.getRuleId()) || (this
				.getRuleId() != null && castOther.getRuleId() != null && this
				.getRuleId().equals(castOther.getRuleId())))
				&& ((this.getIsFeedback() == castOther.getIsFeedback()) || (this
						.getIsFeedback() != null
						&& castOther.getIsFeedback() != null && this
						.getIsFeedback().equals(castOther.getIsFeedback())))
				&& ((this.getFeedbackDesc() == castOther.getFeedbackDesc()) || (this
						.getFeedbackDesc() != null
						&& castOther.getFeedbackDesc() != null && this
						.getFeedbackDesc().equals(castOther.getFeedbackDesc())))
				&& ((this.getBusinessCode() == castOther.getBusinessCode()) || (this
						.getBusinessCode() != null
						&& castOther.getBusinessCode() != null && this
						.getBusinessCode().equals(castOther.getBusinessCode())))
				&& ((this.getHitDesc() == castOther.getHitDesc()) || (this
						.getHitDesc() != null && castOther.getHitDesc() != null && this
						.getHitDesc().equals(castOther.getHitDesc())))
				&& ((this.getPositionDesc() == castOther.getPositionDesc()) || (this
						.getPositionDesc() != null
						&& castOther.getPositionDesc() != null && this
						.getPositionDesc().equals(castOther.getPositionDesc())))
				&& ((this.getEntityKeys() == castOther.getEntityKeys()) || (this
						.getEntityKeys() != null
						&& castOther.getEntityKeys() != null && this
						.getEntityKeys().equals(castOther.getEntityKeys())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRuleId() == null ? 0 : this.getRuleId().hashCode());
		result = 37
				* result
				+ (getIsFeedback() == null ? 0 : this.getIsFeedback()
						.hashCode());
		result = 37
				* result
				+ (getFeedbackDesc() == null ? 0 : this.getFeedbackDesc()
						.hashCode());
		result = 37
				* result
				+ (getBusinessCode() == null ? 0 : this.getBusinessCode()
						.hashCode());
		result = 37 * result
				+ (getHitDesc() == null ? 0 : this.getHitDesc().hashCode());
		result = 37
				* result
				+ (getPositionDesc() == null ? 0 : this.getPositionDesc()
						.hashCode());
		result = 37
				* result
				+ (getEntityKeys() == null ? 0 : this.getEntityKeys()
						.hashCode());
		return result;
	}

}
