package gov.customs.jm.data;

// Generated May 26, 2015 2:43:33 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RuleRelData generated by hbm2java
 */
public class RuleRelData implements java.io.Serializable {

	private RuleRelDataId id;
	private String postRuleDesc;
	private BigDecimal ruleOrder;

	public RuleRelData() {
	}

	public RuleRelData(RuleRelDataId id) {
		this.id = id;
	}

	public RuleRelData(RuleRelDataId id, String postRuleDesc,
			BigDecimal ruleOrder) {
		this.id = id;
		this.postRuleDesc = postRuleDesc;
		this.ruleOrder = ruleOrder;
	}

	public RuleRelDataId getId() {
		return this.id;
	}

	public void setId(RuleRelDataId id) {
		this.id = id;
	}

	public String getPostRuleDesc() {
		return this.postRuleDesc;
	}

	public void setPostRuleDesc(String postRuleDesc) {
		this.postRuleDesc = postRuleDesc;
	}

	public BigDecimal getRuleOrder() {
		return this.ruleOrder;
	}

	public void setRuleOrder(BigDecimal ruleOrder) {
		this.ruleOrder = ruleOrder;
	}

}
