package gov.customs.jm.data;

import java.math.BigDecimal;

// Generated Jun 25, 2015 11:37:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * RuleFeedbackData generated by hbm2java
 */
public class RuleFeedback {
	
	public RuleFeedback(BigDecimal ruleId, Boolean isFeedBack,
			String businessCode, String hitDesc, String positionDesc) {
		super();
		this.ruleId = ruleId;
		this.isFeedBack = isFeedBack;
		this.businessCode = businessCode;
		this.hitDesc = hitDesc;
		this.positionDesc = positionDesc;
	}
	
	public BigDecimal getRuleId() {
		return ruleId;
	}
	public void setRuleId(BigDecimal ruleId) {
		this.ruleId = ruleId;
	}
	public Boolean getIsFeedBack() {
		return isFeedBack;
	}
	public void setIsFeedBack(Boolean isFeedBack) {
		this.isFeedBack = isFeedBack;
	}
	public String getBusinessCode() {
		return businessCode;
	}
	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode;
	}
	public String getHitDesc() {
		return hitDesc;
	}
	public void setHitDesc(String hitDesc) {
		this.hitDesc = hitDesc;
	}
	public String getPositionDesc() {
		return positionDesc;
	}
	public void setPositionDesc(String positionDesc) {
		this.positionDesc = positionDesc;
	}
	private BigDecimal ruleId;
	private Boolean isFeedBack;
	private String businessCode;
	private String hitDesc;
	private String positionDesc;

}
